for i in range(int(input())):
    n=input()
    m=''
    p=0
    while(p<len(n)):
            if(n[p]=='0'):
                m+='0000'
            elif(n[p]=='1'):
                m+='0001'
            elif(n[p]=='2'):
                m+='0010'
            elif(n[p]=='3'):
                m+='0011'
            elif(n[p]=='4'):
                m+='0100'
            elif(n[p]=='5'):
                m+='0101'
            elif(n[p]=='6'):
                m+='0110'
            elif(n[p]=='7'):
                m+='0111'
            elif(n[p]=='8'):
                m+='1000'
            elif(n[p]=='9'):
                m+='1001'
            elif(n[p]=='A'):
                m+='1010'
            elif(n[p]=='B'):
                m+='1011'
            elif(n[p]=='C'):
                m+='1100'
            elif(n[p]=='D'):
                m+='1101'
            elif(n[p]=='E'):
                m+='1110'
            elif(n[p]=='F'):
                m+='1111'
            p+=1
    print(m)